### ISSUE TITLE
Making sure test classes are actually functional

### ISSUE THREAD

**Issue by edgarjc** [jakedeemed/IST311ITERATION1#13]
I will be meeting with our professor to understand how to make the tests properly. I will make sure everyone understands how they work.

**Comment by edgarjc** [comment]
I have completed GameUI, Level1 and Level2 test classes. Still working on the other ones.

**Comment by maxwellkos** [comment]
Wrote the tests for decision1

**Comment by edgarjc** [comment]
Decision2 test class has been completed and it passed
